# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Photogenic' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photogenic

  pod 'Bond', '4.0.0'
  pod 'DateTools'
  pod "ConvenienceKit"
  pod 'Parse'
  pod 'ParseFacebookUtilsV4'
  pod 'ParseUI'
  pod 'MGSwipeTableCell'
  pod 'IQKeyboardManager’
  pod 'RealmSwift'
  pod 'BSForegroundNotification'
  pod 'WDImagePicker', :git => 'https://github.com/justwudi/WDImagePicker.git', :tag => '0.2.2'
end
